<?php

namespace Wiki\WikiBundle\Repository;

/**
 * PageRevisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRevisionRepository extends \Doctrine\ORM\EntityRepository
{
}
