<?php

namespace Wiki\WikiBundle\Repository;

/**
 * UserStatisticRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserStatisticRepository extends \Doctrine\ORM\EntityRepository
{
}
