wiki_wiki_page:
    resource: "@WikiWikiBundle/Controller/PageController.php"
    type:     annotation

wiki_wiki:
    resource: "@WikiWikiBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
