wiki_wiki:
    resource: "@WikiWikiBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

users:
    type: rest
    resource: Wiki\WikiBundle\Controller\UserController
