wiki_wiki_homepage:
    path:     /
    defaults: { _controller: WikiWikiBundle:Default:index }

user:
    type: rest
    resource: "@WikiWikiBundle/Controller/UserController.php"

pages:
    type: rest
    resource: Wiki\WikiBundle\Controller\PageController

revisions:
    type: rest
    resource: Wiki\WikiBundle\Controller\PageRevisionController

ratings:
    type: rest
    resource: Wiki\WikiBundle\Controller\RatingController

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"