Wiki\WikiBundle\Entity\Page:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: slug
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: revisionId
    properties:
        revisionId:
            - NotBlank: ~
            - Type: integer
#        createdAt:
#            - NotBlank: ~
#            - Type: datetime
#        updatedAt:
#            - NotBlank: ~
#            - Type: datetime
        slug:
            - NotBlank: ~
            - Type: string

Wiki\WikiBundle\Entity\PageRevision:
    properties:
        title:
            - NotBlank: ~
            - Type: string
        status:
            - NotBlank: ~
            - Choice:
                choices: [online, pending_validation, canceled, draft]
        content:
            - NotBlank: ~
            - Type: string
        updatedBy:
            - NotBlank: ~
            - Type: integer
#        createdAt:
#            - NotBlank: ~
#            - Type: datetime

Wiki\WikiBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: pseudo
    properties:
        email:
        status:
        password:
        pseudo:
        role:
        createdAt:
        lastConnectedAt:
