Wiki\WikiBundle\Entity\Page:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: slug
    properties:
#        createdAt:
#            - NotBlank: ~
#            - Type: datetime
#        updatedAt:
#            - NotBlank: ~
#            - Type: datetime
        slug:
            - Type: string

Wiki\WikiBundle\Entity\PageRevision:
    properties:
        status:
            - NotBlank: ~
            - Choice:
                choices: [online, pending_validation, canceled, draft]
        content:
            - NotBlank: ~
            - Type: string
#        updatedBy:
#            - NotBlank: ~
#            - Type: integer
#        createdAt:
#            - NotBlank: ~
#            - Type: datetime

#Wiki\WikiBundle\Entity\User:
#    constraints:
#        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
#        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: pseudo
#    properties:
#        username:
#            - NotBlank: ~
#            - Type: string
#        email:
#            - NotBlank: ~
#            - Type: string
#        status:
#            - NotBlank: ~
#            - Choice:
#                choices: [active, banned]
#        password:
#            - NotBlank: ~
#            - Type: string
#        role:
#            - NotBlank: ~
#            - Type: integer
#        createdAt:
#            - NotBlank: ~
#            - Type: string
#        lastConnectedAt:
#            - NotBlank: ~
#            - Type: string



Wiki\WikiBundle\Entity\Rating:
    properties:
        rating:
            - NotBlank: ~
            - Type: integer