Wiki\WikiBundle\Entity\User:
    exclusion_policy: none
    properties:
        id:
            groups: ['user']
        email:
            groups: ['user']
        username:
            groups: ['user']
        enabled:
            groups: ['user']
        password:
            groups: ['user']
        role:
            groups: ['user']
        createdAt:
            groups: ['user']
        last_login:
            groups: ['user']