Wiki\WikiBundle\Entity\PageRevision:
    exclusion_policy: none
    properties:
        id:
            groups: ['pageRevision', 'page']
        status:
            groups: ['pageRevision', 'page']
        content:
            groups: ['pageRevision', 'page']
        updatedBy:
            groups: ['pageRevision', 'page']
        createdAt:
            groups: ['pageRevision', 'page']
        page:
            groups: ['pageRevision']