Wiki\WikiBundle\Entity\Page:
    exclusion_policy: none
    properties:
        id:
            groups: ['page', 'pageRevision']
        createdAt:
            groups: ['page', 'pageRevision']
        updatedAt:
            groups: ['page', 'pageRevision']
        slug:
            groups: ['page', 'pageRevision']
        revisions:
            groups: ['page']