Wiki\WikiBundle\Entity\PageRevision:
    exclusion_policy: none
    attributes:
        id:
            groups: ['pageRevision', 'page']
        title:
            groups: ['pageRevision', 'page']
        status:
            groups: ['pageRevision', 'page']
        content:
            groups: ['pageRevision', 'page']
        updatedBy:
            groups: ['pageRevision', 'page']
        createdAt:
            groups: ['pageRevision', 'page']
        updatedAt:
            groups: ['pageRevision', 'page']
        revisionVersion:
            groups: ['pageRevision', 'page']
        page:
            groups: ['pageRevision']










